language: java

install: mvn install -DskipTests=true

before_install:
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  - export ANDROID_HOME=~/build/tjerkw/Android-SlideExpandableListView/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android list sdk
  - android update sdk --filter 14 --no-ui --obsolete --force
  - android update sdk --filter 1,2 --no-ui --obsolete --force
#  - android update sdk --filter 1,2,5,9 --no-ui --force
